"""Build native, editable Mathcad XMCD worksheets from Python."""

from .document import Area, MathRegion, PageBreak, PageSettings, ResultFormat, TextRegion, Worksheet
from .expressions import (
    Break,
    Call,
    Continue,
    Define,
    Derivative,
    Evaluate,
    Expr,
    For,
    Function,
    Given,
    If,
    Imaginary,
    Integral,
    Matrix,
    Number,
    Operator,
    Otherwise,
    Placeholder,
    Product,
    Program,
    Range,
    Return,
    Sequence,
    Solver,
    String,
    Sum,
    Symbol,
    Symbolic,
    TryCatch,
    While,
    expr,
    f,
)
from .plots import Trace, XYPlot
from .validation import CalculationError, ValidationError, calculation_errors, validate

__all__ = [
    "Area",
    "Break",
    "CalculationError",
    "Call",
    "Continue",
    "Define",
    "Derivative",
    "Evaluate",
    "Expr",
    "For",
    "Function",
    "Given",
    "If",
    "Imaginary",
    "Integral",
    "MathRegion",
    "Matrix",
    "Number",
    "Operator",
    "Otherwise",
    "PageBreak",
    "PageSettings",
    "Placeholder",
    "Product",
    "Program",
    "Range",
    "ResultFormat",
    "Return",
    "Sequence",
    "Solver",
    "String",
    "Sum",
    "Symbol",
    "Symbolic",
    "TextRegion",
    "Trace",
    "TryCatch",
    "ValidationError",
    "While",
    "Worksheet",
    "XYPlot",
    "calculation_errors",
    "expr",
    "f",
    "validate",
]
