"""Generate a live-calculation acceptance worksheet on Linux."""

from pathlib import Path

from xmcd import (
    Derivative,
    Function,
    If,
    Integral,
    Matrix,
    Otherwise,
    Program,
    Range,
    Sum,
    Symbol,
    Worksheet,
)


def build():
    sheet = Worksheet("Core XMCD acceptance")
    x = Symbol("x")
    sheet.text("XMCD: formulas generated by Python", top=24)
    sheet.define(Symbol("a"), 2, tag="input-a")
    sheet.evaluate(Symbol("a") ** 3 + 1, tag="scalar-9")
    sheet.define(Symbol("A"), Matrix([[1, 2], [3, 4]]), height=50)
    sheet.evaluate(Symbol("A")[0, 1], tag="index-2")
    sheet.evaluate(Symbol("A").determinant(), tag="det-minus2")
    sheet.define(Function(Symbol("g"), [x]), x**3 + 2 * x)
    sheet.evaluate(Symbol("g")(2), tag="function-12")
    sheet.define(x, 2)
    sheet.evaluate(Derivative(Symbol("g")(x), x), tag="derivative-14", height=45)
    sheet.evaluate(Integral(x**2, x, 0, 1), tag="integral-third", height=50)
    sheet.evaluate(Sum(x, x, 1, 5), tag="sum-15", height=50)
    sheet.define(Function(Symbol("positive"), [x]), Program(If(x > 0, x), Otherwise(-x)), height=55)
    sheet.evaluate(Symbol("positive")(-3), tag="program-3")
    sheet.define(Symbol("i"), Range(0, 4))
    sheet.define(Symbol("v")[Symbol("i")], Symbol("i") ** 2)
    sheet.evaluate(Symbol("v")[3], tag="vector-9")
    return sheet


if __name__ == "__main__":
    Path("output").mkdir(exist_ok=True)
    print(build().write("output/core.xmcd"))
