"""Native solve blocks, including a parameterized solve function."""

from pathlib import Path

from xmcd import Function, Given, Solver, SolverKind, Symbol, Worksheet


def build():
    sheet = Worksheet("Solve block acceptance", tolerance=1e-8, constraint_tolerance=1e-8)
    x, y, p = (Symbol(n) for n in ("x", "y", "p"))
    sheet.text("Given / Find generated by Python", top=24)
    sheet.define(x, 1)
    sheet.define(y, 1)
    sheet.math(Given())
    sheet.math((x + y).eq(5))
    sheet.math((x - y).eq(1))
    sheet.define(Symbol("solution"), Solver(SolverKind.FIND)(x, y))
    sheet.evaluate(Symbol("solution"), tag="solution-3-2", height=50)
    sheet.define(x, 2)
    sheet.math(Given())
    sheet.math((x**2).eq(p))
    sheet.define(Function(Symbol("positive_root"), [p]), Solver(SolverKind.FIND)(x))
    sheet.evaluate(Symbol("positive_root")(9), tag="parameterized-3")
    return sheet


if __name__ == "__main__":
    Path("output").mkdir(exist_ok=True)
    print(build().write("output/solvers.xmcd"))
